[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Fort Collins (053005) Daily Precipitation"
SubTitleString = "High precipitation are hot colors"

[SubProduct 1]

GraphType = "Raster"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "COOP:053005.ACIS.pcpn.Day~RCC-ACIS"
SymbolTablePath = "raster-precip-highbad-classify.csv"
RasterGraphLegendPosition = "Right"
