[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Fort Collins (053005) Maximum Daily Air Temperature"
SubTitleString = "High temperatures are hot colors"

[SubProduct 1]

GraphType = "Raster"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "COOP:053005.ACIS.maxt.Day~RCC-ACIS"
SymbolTablePath = "raster-maxt-highbad-classify.csv"
RasterGraphLegendPosition = "Right"
