[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Poudre River at Fort Collins (06752260) Daily Average Streamflow"
SubTitleString = "Low flow are hot colors"

[SubProduct 1]

GraphType = "Raster"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "06752260.USGS.Streamflow.Day~HydroBase"
SymbolTablePath = "raster-streamflow-lowbad-classify.csv"
RasterGraphLegendPosition = "Right"
