[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
#ShowDrawingAreaOutline = "True"

[SubProduct 1]

GraphType = "Line"
RightYAxisTitlePosition = "RightOfAxis"
RightYAxisTitleRotation = "90"
RightYAxisTitleString = "Precipitation (in)"
RightYAxisGraphType = "Line"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "ts1..MyData.Day"
TSAlias = "ts1"

[Data 1.2]

TSID = "ts2..MyData.Day"
TSAlias = "ts2"
YAxis = "Right"
