[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Comparison of Running Average for Diversion Data"

[SubProduct 1]

GraphType = "Line"

[Data 1.1]

TSID = "0100501.DWR.DivTotal.Month~HydroBase"
TSAlias = "Center"

[Data 1.2]

TSID = "0100501.DWR.DivTotal.Month~HydroBase"
TSAlias = "NYear"

[Data 1.3]

TSID = "0100501.DWR.DivTotal.Month~HydroBase"
