[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Traces Created from Historical Time Series"

[SubProduct 1]

GraphType = "Line"

[Data 1.1]

TSID = "08235350.USGS.Streamflow.Day~HydroBase"

[Data 1.2]

TSID = "08235350.USGS.Streamflow.Day~HydroBase"

[Data 1.3]

TSID = "08235350.USGS.Streamflow.Day~HydroBase"

[Data 1.4]

TSID = "08235350.USGS.Streamflow.Day~HydroBase"

[Data 1.5]

TSID = "08235350.USGS.Streamflow.Day~HydroBase"
