[Product]

ProductType = "Graph"
TotalHeight = "400"
TotalWidth = "600"

[SubProduct 1]

GraphType = "Point"
LeftYAxisIgnoreUnits = "false"

[Data 1.1]

LineStyle = "None"
SymbolSize = "5"
SymbolStyle = "Circle-Hollow"
TSAlias = "ts1_Zeros_Month"
TSID = "ts1..Streamflow.Month"

[SubProduct 2]

GraphType = "Line"

[Data 2.1]

TSAlias = "ts1_Zeros_Month_NonexceedanceProbability"
TSID = "ts1..Streamflow-Running-NonexceedanceProbability.Month"
