[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Plot for Test_FillRegression_Streamflow_Month_OneEquation"

[SubProduct 1]

GraphType = "Line"

[Data 1.1]

Color = Red
TSID = "394308105413800.USGS.Streamflow.Month~DateValue~C:\Develop\TSTool_SourceBuild\TSTool\test\regression\commands\general\FillRegression\Data\streamflow-month.dv"
TSAlias = "AboveGeorgetown"
SymbolSize = "5"
SymbolStyle = "Circle-Filled"

[Data 1.2]

Color = Blue
TSID = "394359105411900.USGS.Streamflow.Month~DateValue~C:\Develop\TSTool_SourceBuild\TSTool\test\regression\commands\general\FillRegression\Data\streamflow-month.dv"
TSAlias = "BelowGeorgetown"
SymbolSize = "5"
SymbolStyle = "Circle-Filled"
FlaggedDataSymbolStyle = "Circle-Hollow"

