#HeaderRevision 0
#
# File generated by...
# program:   StateDMI 1.17.09 (2005-02-14)
# user:      rrb
# date:      Wed Feb 23 23:03:27 :00 2005
# host:      host unknown
# directory: C:\Cdss\DataSets\Colorado\StateDMI
# command:   StateDMI -home \CDSS 
#-----------------------------------------------------------------------
# Last command file: "C:\Cdss\DataSets\Colorado\StateDMI\cm2004.cds.StateDMI"
#
# Commands used to generate output:
#
# setOutputPeriod(1909,2004)
# readCULocationsFromStateCU("..\StateCU\cm2004\cm2004.str")
# setDiversionAggregateFromList(ListFile="..\StateCU_SupportingFiles\colorado.agg",IDCol=1,PartIDsCol=2,PartsListedHow=InRow,PartIDsColMax=72)
# createCropPatternTSForCULocations(ID="*",Units="ACRE")
# readCropPatternTSFromHydroBase(ID="*")
# translateCropPatternTS(ID="*",OldCropType="ORCHARD W/O COVER",NewCropType="ORCHARD_WO_COVER")
# fillCropPatternTSConstant(ID="*",CropType="*",FillStart="1993",FillEnd="1993",Constant=0)
# fillCropPatternTSConstant(ID="*",CropType="*",FillStart="2000",FillEnd="2000",Constant=0)
# fillCropPatternTSRepeat(ID="*",CropType="*",FillStart="1909",FillEnd="1993",FillDirection="Backward")
# fillCropPatternTSRepeat(ID="*",CropType="*",FillStart="1993",FillEnd="2000",FillDirection="Forward")
# fillCropPatternTSRepeat(ID="*",CropType="*",FillStart="2000",FillEnd="2004",FillDirection="Forward")
# writeCropPatternTSToStateCU(OutputFile="..\StateCU\cm2005\cm2005.cds",WriteCropArea="True",WriteHow="OverwriteFile")
#----
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase on denver3.dwr.state.co.us
# HydroBase.db_version:  design version: 20050201  last data change: 20050201
# HydroBase table structure for software is at least 2004070120040701
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Record 1 format (i4,1x,a12,8x,f10.3,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Beginning year of data.
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a20,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0).
#>                      Fractions should add to 1.0.
#>  Acres       acres:  Acreage for crop (part of total).
#>
#>Yr  CULocation     TotalArea       NCrop
#>-exb----------exxxxxxxxb--------eb--------e
#>     CropName          Fraction    Acres
#>xxxb------------------eb--------eb--------e
#>EndHeader
      2000           2004 ACRE
2000 360645                 355.962         1
     GRASS_PASTURE            1.000   355.962
2000 360649                 736.309         1
     GRASS_PASTURE            1.000   736.309
2000 360660                 298.978         1
     GRASS_PASTURE            1.000   298.978
2000 360662                1184.399         2
     ALFALFA                  0.085   100.517
2000 360800                 209.766         1
     GRASS_PASTURE            1.000   209.766
2000 360801                 328.314         1
     GRASS_PASTURE            1.000   328.314
2000 360868                 130.260         1
     GRASS_PASTURE            1.000   130.260
2000 380516                 269.791         4
     ALFALFA                  0.000     0.000
2000 380528                 273.248         3
     ALFALFA                  0.000     0.000
2000 380545                 170.351         1
     GRASS_PASTURE            1.000   170.351
2000 380569                 656.492         2
     ALFALFA                  0.000     0.000
2000 380606                 119.565         1
     GRASS_PASTURE            1.000   119.565
2000 380618                 195.712         2
     ALFALFA                  0.000     0.000
2000 380639                 195.479         1
     GRASS_PASTURE            1.000   195.479
2000 380651                 470.791         3
     ALFALFA                  0.000     0.000
2000 380659                  42.218         2
     GRASS_PASTURE            0.165     6.984
2000 380663                 150.226         3
     ALFALFA                  0.000     0.000
2000 380688                 130.362         2
     ALFALFA                  0.000     0.000
2000 380800                 139.596         1
     GRASS_PASTURE            1.000   139.596
2000 380822                  62.079         1
     GRASS_PASTURE            1.000    62.079
2000 380838                  32.492         1
     GRASS_PASTURE            1.000    32.492
2000 380840                 320.663         2
     ALFALFA                  0.000     0.000
2000 380861                 164.286         1
     GRASS_PASTURE            1.000   164.286
2000 380880                 785.098         2
     ALFALFA                  0.000     0.000
2000 380881                 253.908         2
     ALFALFA                  0.000     0.000
2000 380890                 136.346         1
     GRASS_PASTURE            1.000   136.346
2000 380893                 512.291         2
     ALFALFA                  0.000     0.000
2000 380902                 995.745         3
     ALFALFA                  0.000     0.000
2000 380925                 520.167         3
     ALFALFA                  0.000     0.000
2000 380930                  34.005         1
     GRASS_PASTURE            1.000    34.005
2000 380939                 125.433         2
     ALFALFA                  0.000     0.000
2000 380959                 141.837         2
     ALFALFA                  0.000     0.000
2000 380966                  91.325         3
     ALFALFA                  0.000     0.000
2000 380968                 296.481         3
     ALFALFA                  0.000     0.000
2000 380981                 202.986         2
     GRASS_PASTURE            1.000   202.986
2000 380989                  70.913         1
     GRASS_PASTURE            1.000    70.913
2000 380994                 174.339         2
     ALFALFA                  0.000     0.000
2000 380996                 172.852         2
     ALFALFA                  0.000     0.000
2000 381012                 181.382         2
     ALFALFA                  0.000     0.000
2000 381018                  16.566         2
     ALFALFA                  0.000     0.000
2000 381038                1176.064         3
     ALFALFA                  0.000     0.000
2000 381062                  76.950         2
     ALFALFA                  0.000     0.000
2000 381066                 424.051         2
     ALFALFA                  0.000     0.000
2000 381095                 331.320         1
     GRASS_PASTURE            1.000   331.320
2000 381101                  38.758         1
     GRASS_PASTURE            1.000    38.758
2000 381104                 180.260         2
     ALFALFA                  0.000     0.000
2000 381121                  22.627         1
     GRASS_PASTURE            1.000    22.627
2000 381132                   7.833         1
     GRASS_PASTURE            1.000     7.833
2000 381481                 345.953         3
     ALFALFA                  0.000     0.000
2000 381661                 306.270         2
     ALFALFA                  0.000     0.000
2000 390532                 112.767         3
     CORN_GRAIN               0.020     2.244
2000 390539                  92.705         1
     GRASS_PASTURE            1.000    92.705
2000 390540                 555.061         2
     GRASS_PASTURE            0.875   485.511
2000 390548                  58.607         1
     GRASS_PASTURE            1.000    58.607
2000 390562                 111.154         1
     GRASS_PASTURE            1.000   111.154
2000 390585                 138.149         2
     GRASS_PASTURE            0.927   128.045
2000 390590                 135.376         2
     GRASS_PASTURE            1.000   135.376
2000 390610                 346.992         1
     GRASS_PASTURE            1.000   346.992
2000 390612                1097.901         5
     ALFALFA                  0.027    30.099
2000 390635                 127.131         3
     ALFALFA                  0.733    93.200
2000 390638                  58.381         1
     GRASS_PASTURE            1.000    58.381
2000 390645                1167.978         5
     ALFALFA                  0.029    33.521
2000 390825                 488.042         3
     ALFALFA                  0.386   188.297
2000 390990                 287.043         3
     ALFALFA                  0.430   123.532
2000 450514                 705.327         6
     ALFALFA                  0.000     0.000
2000 450584                 475.420         2
     ALFALFA                  0.000     0.000
2000 450616                 385.552         1
     GRASS_PASTURE            1.000   385.552
2000 450632                 445.768         2
     ALFALFA                  0.000     0.000
2000 450635                 157.981         2
     ALFALFA                  0.000     0.000
2000 450638                 144.530         2
     GRASS_PASTURE            1.000   144.530
2000 450668                 991.719         4
     ALFALFA                  0.000     0.000
2000 450685                 395.703         2
     GRASS_PASTURE            1.000   395.703
2000 450693                 738.893         2
     ALFALFA                  0.667   493.029
2000 450810                 125.679         2
     ALFALFA                  0.000     0.000
2000 450818                 690.592         3
     ALFALFA                  0.000     0.000
2000 450861                 443.143         3
     ALFALFA                  0.000     0.000
2000 450969                1864.353         5
     ALFALFA                  0.000     0.000
2000 500526                 142.766         1
     GRASS_PASTURE            1.000   142.766
2000 500539                 247.029         1
     GRASS_PASTURE            1.000   247.029
2000 500582                 392.679         1
     GRASS_PASTURE            1.000   392.679
2000 500585                 205.650         1
     GRASS_PASTURE            1.000   205.650
2000 500593                1999.619         1
     GRASS_PASTURE            1.000  1999.619
2000 500598                  50.099         1
     GRASS_PASTURE            1.000    50.099
2000 500601                 192.978         1
     GRASS_PASTURE            1.000   192.978
2000 500606                 835.312         1
     GRASS_PASTURE            1.000   835.312
2000 500612                 152.121         1
     GRASS_PASTURE            1.000   152.121
2000 500613                  61.849         1
     GRASS_PASTURE            1.000    61.849
2000 500628                 243.741         2
     ALFALFA                  0.000     0.000
2000 500632                 154.777         1
     GRASS_PASTURE            1.000   154.777
2000 500653                 445.836         1
     GRASS_PASTURE            1.000   445.836
2000 500654                 322.157         1
     GRASS_PASTURE            1.000   322.157
2000 500656                 180.006         1
     GRASS_PASTURE            1.000   180.006
2000 510529                2878.464         2
     ALFALFA                  0.000     0.000
2000 510546                 524.176         1
     GRASS_PASTURE            1.000   524.176
2000 510585                 198.078         1
     GRASS_PASTURE            1.000   198.078
2000 510594                1003.344         1
     GRASS_PASTURE            1.000  1003.344
2000 510629                 270.182         1
     GRASS_PASTURE            1.000   270.182
2000 510660                 366.511         1
     GRASS_PASTURE            1.000   366.511
2000 510699                 198.748         1
     GRASS_PASTURE            1.000   198.748
2000 510810                 386.397         2
     ALFALFA                  0.237    91.446
2000 510829                 530.631         1
     GRASS_PASTURE            1.000   530.631
2000 510831                 436.360         1
     GRASS_PASTURE            1.000   436.360
2000 510848                1693.502         1
     GRASS_PASTURE            1.000  1693.502
2000 510858                  35.332         1
     GRASS_PASTURE            1.000    35.332
2000 510880                 131.464         1
     GRASS_PASTURE            1.000   131.464
2000 510883                 145.622         1
     GRASS_PASTURE            1.000   145.622
2000 510893                 770.192         1
     GRASS_PASTURE            1.000   770.192
2000 510924                 276.273         1
     GRASS_PASTURE            1.000   276.273
2000 510934                 170.710         1
     GRASS_PASTURE            1.000   170.710
2000 510939                  35.289         1
     GRASS_PASTURE            1.000    35.289
2000 510941                 603.425         2
     GRASS_PASTURE            0.509   307.303
2000 510948                 588.144         1
     GRASS_PASTURE            1.000   588.144
2000 511149                 124.666         1
     GRASS_PASTURE            1.000   124.666
2000 520559                 123.302         1
     GRASS_PASTURE            1.000   123.302
2000 520658                  43.287         1
     GRASS_PASTURE            1.000    43.287
2000 530555                1780.727         3
     ALFALFA                  0.035    61.452
2000 530621                 497.605         1
     GRASS_PASTURE            1.000   497.605
2000 530632                  17.355         1
     GRASS_PASTURE            1.000    17.355
2000 530800                 794.342         1
     GRASS_PASTURE            1.000   794.342
2000 530883                 322.713         2
     ALFALFA                  0.741   239.189
2000 531082                 112.110         1
     GRASS_PASTURE            1.000   112.110
2000 950001               28899.877        11
     ALFALFA                  0.352 10173.014
2000 950010                2589.792         4
     ALFALFA                  0.005    12.055
2000 950011                2905.585         6
     ALFALFA                  0.013    39.195
2000 950050                4296.738         7
     ALFALFA                  0.010    43.831
2000 51_ADC001              550.505         1
     GRASS_PASTURE            1.000   550.505
2000 51_ADC002              785.286         1
     GRASS_PASTURE            1.000   785.286
2000 51_ADC003              849.278         1
     GRASS_PASTURE            1.000   849.278
2000 51_ADC004              512.210         1
     GRASS_PASTURE            1.000   512.210
2000 51_ADC005             1661.403         1
     GRASS_PASTURE            1.000  1661.403
2000 51_ADC006              625.713         1
     GRASS_PASTURE            1.000   625.713
2000 51_ADC008              875.152         1
     GRASS_PASTURE            1.000   875.152
2000 51_ADC009              896.785         1
     GRASS_PASTURE            1.000   896.785
2000 51_ADC010             1170.506         1
     GRASS_PASTURE            1.000  1170.506
2000 51_ADC011              716.316         1
     GRASS_PASTURE            1.000   716.316
2000 50_ADC012             1793.950         1
     GRASS_PASTURE            1.000  1793.950
2000 50_ADC013             1986.270         1
     GRASS_PASTURE            1.000  1986.270
2000 50_ADC014             1416.725         1
     GRASS_PASTURE            1.000  1416.725
2000 50_ADC015             1430.841         1
     GRASS_PASTURE            1.000  1430.841
2000 50_ADC016              931.044         1
     GRASS_PASTURE            1.000   931.044
2000 36_ADC018              609.981         1
     GRASS_PASTURE            1.000   609.981
2000 36_ADC019             2081.370         1
     GRASS_PASTURE            1.000  2081.370
2000 50_ADC020             1643.003         1
     GRASS_PASTURE            1.000  1643.003
2000 52_ADC021             1901.956         2
     GRASS_PASTURE            0.945  1797.471
2000 53_ADC022              307.526         1
     GRASS_PASTURE            1.000   307.526
2000 53_ADC023             1376.759         1
     GRASS_PASTURE            1.000  1376.759
2000 53_ADC024             1262.373         1
     GRASS_PASTURE            1.000  1262.373
2000 53_ADC025              822.065         1
     GRASS_PASTURE            1.000   822.065
2000 53_ADC026              957.884         2
     GRASS_PASTURE            0.948   907.916
2000 53_ADC028             1518.271         2
     GRASS_PASTURE            0.991  1504.469
2000 53_ADC032             1867.921         2
     GRASS_PASTURE            0.902  1684.993
2000 38_ADC033              703.560         4
     GRASS_PASTURE            1.000   703.560
2000 38_ADC034             1544.918         1
     GRASS_PASTURE            1.000  1544.918
2000 38_ADC035              358.106         3
     GRASS_PASTURE            1.000   358.106
2000 38_ADC036              599.973         2
     GRASS_PASTURE            1.000   599.973
2000 38_ADC038             1021.048         3
     GRASS_PASTURE            1.000  1021.048
2000 38_ADC039             1025.199         3
     GRASS_PASTURE            1.000  1025.199
2000 38_ADC040             1106.566         4
     ALFALFA                  0.000     0.000
2000 39_ADC041             1431.832         3
     GRASS_PASTURE            0.981  1403.975
2000 45_ADC042             1406.261         3
     GRASS_PASTURE            0.920  1293.762
2000 45_ADC043             2265.728         4
     GRASS_PASTURE            0.748  1694.203
2000 45_ADC044             2175.626         4
     GRASS_PASTURE            0.837  1821.045
2000 39_ADC045             1324.179         4
     SMALL_GRAINS             0.008    10.233
2000 45_ADC046             1171.803         3
     SMALL_GRAINS             0.023    26.863
2000 45_ADC048             2794.639         4
     GRASS_PASTURE            0.737  2058.816
2001 360645                 355.962         1
     GRASS_PASTURE            1.000   355.962
2001 360649                 736.309         1
     GRASS_PASTURE            1.000   736.309
2001 360660                 298.978         1
     GRASS_PASTURE            1.000   298.978
2001 360662                1184.399         2
     ALFALFA                  0.085   100.517
2001 360800                 209.766         1
     GRASS_PASTURE            1.000   209.766
2001 360801                 328.314         1
     GRASS_PASTURE            1.000   328.314
2001 360868                 130.260         1
     GRASS_PASTURE            1.000   130.260
2001 380516                 269.791         4
     ALFALFA                  0.000     0.000
2001 380528                 273.248         3
     ALFALFA                  0.000     0.000
2001 380545                 170.351         1
     GRASS_PASTURE            1.000   170.351
2001 380569                 656.492         2
     ALFALFA                  0.000     0.000
2001 380606                 119.565         1
     GRASS_PASTURE            1.000   119.565
2001 380618                 195.712         2
     ALFALFA                  0.000     0.000
2001 380639                 195.479         1
     GRASS_PASTURE            1.000   195.479
2001 380651                 470.791         3
     ALFALFA                  0.000     0.000
2001 380659                  42.218         2
     GRASS_PASTURE            0.165     6.984
2001 380663                 150.226         3
     ALFALFA                  0.000     0.000
2001 380688                 130.362         2
     ALFALFA                  0.000     0.000
2001 380800                 139.596         1
     GRASS_PASTURE            1.000   139.596
2001 380822                  62.079         1
     GRASS_PASTURE            1.000    62.079
2001 380838                  32.492         1
     GRASS_PASTURE            1.000    32.492
2001 380840                 320.663         2
     ALFALFA                  0.000     0.000
2001 380861                 164.286         1
     GRASS_PASTURE            1.000   164.286
2001 380880                 785.098         2
     ALFALFA                  0.000     0.000
2001 380881                 253.908         2
     ALFALFA                  0.000     0.000
2001 380890                 136.346         1
     GRASS_PASTURE            1.000   136.346
2001 380893                 512.291         2
     ALFALFA                  0.000     0.000
2001 380902                 995.745         3
     ALFALFA                  0.000     0.000
2001 380925                 520.167         3
     ALFALFA                  0.000     0.000
2001 380930                  34.005         1
     GRASS_PASTURE            1.000    34.005
2001 380939                 125.433         2
     ALFALFA                  0.000     0.000
2001 380959                 141.837         2
     ALFALFA                  0.000     0.000
2001 380966                  91.325         3
     ALFALFA                  0.000     0.000
2001 380968                 296.481         3
     ALFALFA                  0.000     0.000
2001 380981                 202.986         2
     GRASS_PASTURE            1.000   202.986
2001 380989                  70.913         1
     GRASS_PASTURE            1.000    70.913
2001 380994                 174.339         2
     ALFALFA                  0.000     0.000
2001 380996                 172.852         2
     ALFALFA                  0.000     0.000
2001 381012                 181.382         2
     ALFALFA                  0.000     0.000
2001 381018                  16.566         2
     ALFALFA                  0.000     0.000
2001 381038                1176.064         3
     ALFALFA                  0.000     0.000
2001 381062                  76.950         2
     ALFALFA                  0.000     0.000
2001 381066                 424.051         2
     ALFALFA                  0.000     0.000
2001 381095                 331.320         1
     GRASS_PASTURE            1.000   331.320
2001 381101                  38.758         1
     GRASS_PASTURE            1.000    38.758
2001 381104                 180.260         2
     ALFALFA                  0.000     0.000
2001 381121                  22.627         1
     GRASS_PASTURE            1.000    22.627
2001 381132                   7.833         1
     GRASS_PASTURE            1.000     7.833
2001 381481                 345.953         3
     ALFALFA                  0.000     0.000
2001 381661                 306.270         2
     ALFALFA                  0.000     0.000
2001 390532                 112.767         3
     CORN_GRAIN               0.020     2.244
2001 390539                  92.705         1
     GRASS_PASTURE            1.000    92.705
2001 390540                 555.061         2
     GRASS_PASTURE            0.875   485.511
2001 390548                  58.607         1
     GRASS_PASTURE            1.000    58.607
2001 390562                 111.154         1
     GRASS_PASTURE            1.000   111.154
2001 390585                 138.149         2
     GRASS_PASTURE            0.927   128.045
2001 390590                 135.376         2
     GRASS_PASTURE            1.000   135.376
2001 390610                 346.992         1
     GRASS_PASTURE            1.000   346.992
2001 390612                1097.901         5
     ALFALFA                  0.027    30.099
2001 390635                 127.131         3
     ALFALFA                  0.733    93.200
2001 390638                  58.381         1
     GRASS_PASTURE            1.000    58.381
2001 390645                1167.978         5
     ALFALFA                  0.029    33.521
2001 390825                 488.042         3
     ALFALFA                  0.386   188.297
2001 390990                 287.043         3
     ALFALFA                  0.430   123.532
2001 450514                 705.327         6
     ALFALFA                  0.000     0.000
2001 450584                 475.420         2
     ALFALFA                  0.000     0.000
2001 450616                 385.552         1
     GRASS_PASTURE            1.000   385.552
2001 450632                 445.768         2
     ALFALFA                  0.000     0.000
2001 450635                 157.981         2
     ALFALFA                  0.000     0.000
2001 450638                 144.530         2
     GRASS_PASTURE            1.000   144.530
2001 450668                 991.719         4
     ALFALFA                  0.000     0.000
2001 450685                 395.703         2
     GRASS_PASTURE            1.000   395.703
2001 450693                 738.893         2
     ALFALFA                  0.667   493.029
2001 450810                 125.679         2
     ALFALFA                  0.000     0.000
2001 450818                 690.592         3
     ALFALFA                  0.000     0.000
2001 450861                 443.143         3
     ALFALFA                  0.000     0.000
2001 450969                1864.353         5
     ALFALFA                  0.000     0.000
2001 500526                 142.766         1
     GRASS_PASTURE            1.000   142.766
2001 500539                 247.029         1
     GRASS_PASTURE            1.000   247.029
2001 500582                 392.679         1
     GRASS_PASTURE            1.000   392.679
2001 500585                 205.650         1
     GRASS_PASTURE            1.000   205.650
2001 500593                1999.619         1
     GRASS_PASTURE            1.000  1999.619
2001 500598                  50.099         1
     GRASS_PASTURE            1.000    50.099
2001 500601                 192.978         1
     GRASS_PASTURE            1.000   192.978
2001 500606                 835.312         1
     GRASS_PASTURE            1.000   835.312
2001 500612                 152.121         1
     GRASS_PASTURE            1.000   152.121
2001 500613                  61.849         1
     GRASS_PASTURE            1.000    61.849
2001 500628                 243.741         2
     ALFALFA                  0.000     0.000
2001 500632                 154.777         1
     GRASS_PASTURE            1.000   154.777
2001 500653                 445.836         1
     GRASS_PASTURE            1.000   445.836
2001 500654                 322.157         1
     GRASS_PASTURE            1.000   322.157
2001 500656                 180.006         1
     GRASS_PASTURE            1.000   180.006
2001 510529                2878.464         2
     ALFALFA                  0.000     0.000
2001 510546                 524.176         1
     GRASS_PASTURE            1.000   524.176
2001 510585                 198.078         1
     GRASS_PASTURE            1.000   198.078
2001 510594                1003.344         1
     GRASS_PASTURE            1.000  1003.344
2001 510629                 270.182         1
     GRASS_PASTURE            1.000   270.182
2001 510660                 366.511         1
     GRASS_PASTURE            1.000   366.511
2001 510699                 198.748         1
     GRASS_PASTURE            1.000   198.748
2001 510810                 386.397         2
     ALFALFA                  0.237    91.446
2001 510829                 530.631         1
     GRASS_PASTURE            1.000   530.631
2001 510831                 436.360         1
     GRASS_PASTURE            1.000   436.360
2001 510848                1693.502         1
     GRASS_PASTURE            1.000  1693.502
2001 510858                  35.332         1
     GRASS_PASTURE            1.000    35.332
2001 510880                 131.464         1
     GRASS_PASTURE            1.000   131.464
2001 510883                 145.622         1
     GRASS_PASTURE            1.000   145.622
2001 510893                 770.192         1
     GRASS_PASTURE            1.000   770.192
2001 510924                 276.273         1
     GRASS_PASTURE            1.000   276.273
2001 510934                 170.710         1
     GRASS_PASTURE            1.000   170.710
2001 510939                  35.289         1
     GRASS_PASTURE            1.000    35.289
2001 510941                 603.425         2
     GRASS_PASTURE            0.509   307.303
2001 510948                 588.144         1
     GRASS_PASTURE            1.000   588.144
2001 511149                 124.666         1
     GRASS_PASTURE            1.000   124.666
2001 520559                 123.302         1
     GRASS_PASTURE            1.000   123.302
2001 520658                  43.287         1
     GRASS_PASTURE            1.000    43.287
2001 530555                1780.727         3
     ALFALFA                  0.035    61.452
2001 530621                 497.605         1
     GRASS_PASTURE            1.000   497.605
2001 530632                  17.355         1
     GRASS_PASTURE            1.000    17.355
2001 530800                 794.342         1
     GRASS_PASTURE            1.000   794.342
2001 530883                 322.713         2
     ALFALFA                  0.741   239.189
2001 531082                 112.110         1
     GRASS_PASTURE            1.000   112.110
2001 950001               28899.877        11
     ALFALFA                  0.352 10173.014
2001 950010                2589.792         4
     ALFALFA                  0.005    12.055
2001 950011                2905.585         6
     ALFALFA                  0.013    39.195
2001 950050                4296.738         7
     ALFALFA                  0.010    43.831
2001 51_ADC001              550.505         1
     GRASS_PASTURE            1.000   550.505
2001 51_ADC002              785.286         1
     GRASS_PASTURE            1.000   785.286
2001 51_ADC003              849.278         1
     GRASS_PASTURE            1.000   849.278
2001 51_ADC004              512.210         1
     GRASS_PASTURE            1.000   512.210
2001 51_ADC005             1661.403         1
     GRASS_PASTURE            1.000  1661.403
2001 51_ADC006              625.713         1
     GRASS_PASTURE            1.000   625.713
2001 51_ADC008              875.152         1
     GRASS_PASTURE            1.000   875.152
2001 51_ADC009              896.785         1
     GRASS_PASTURE            1.000   896.785
2001 51_ADC010             1170.506         1
     GRASS_PASTURE            1.000  1170.506
2001 51_ADC011              716.316         1
     GRASS_PASTURE            1.000   716.316
2001 50_ADC012             1793.950         1
     GRASS_PASTURE            1.000  1793.950
2001 50_ADC013             1986.270         1
     GRASS_PASTURE            1.000  1986.270
2001 50_ADC014             1416.725         1
     GRASS_PASTURE            1.000  1416.725
2001 50_ADC015             1430.841         1
     GRASS_PASTURE            1.000  1430.841
2001 50_ADC016              931.044         1
     GRASS_PASTURE            1.000   931.044
2001 36_ADC018              609.981         1
     GRASS_PASTURE            1.000   609.981
2001 36_ADC019             2081.370         1
     GRASS_PASTURE            1.000  2081.370
2001 50_ADC020             1643.003         1
     GRASS_PASTURE            1.000  1643.003
2001 52_ADC021             1901.956         2
     GRASS_PASTURE            0.945  1797.471
2001 53_ADC022              307.526         1
     GRASS_PASTURE            1.000   307.526
2001 53_ADC023             1376.759         1
     GRASS_PASTURE            1.000  1376.759
2001 53_ADC024             1262.373         1
     GRASS_PASTURE            1.000  1262.373
2001 53_ADC025              822.065         1
     GRASS_PASTURE            1.000   822.065
2001 53_ADC026              957.884         2
     GRASS_PASTURE            0.948   907.916
2001 53_ADC028             1518.271         2
     GRASS_PASTURE            0.991  1504.469
2001 53_ADC032             1867.921         2
     GRASS_PASTURE            0.902  1684.993
2001 38_ADC033              703.560         4
     GRASS_PASTURE            1.000   703.560
2001 38_ADC034             1544.918         1
     GRASS_PASTURE            1.000  1544.918
2001 38_ADC035              358.106         3
     GRASS_PASTURE            1.000   358.106
2001 38_ADC036              599.973         2
     GRASS_PASTURE            1.000   599.973
2001 38_ADC038             1021.048         3
     GRASS_PASTURE            1.000  1021.048
2001 38_ADC039             1025.199         3
     GRASS_PASTURE            1.000  1025.199
2001 38_ADC040             1106.566         4
     ALFALFA                  0.000     0.000
2001 39_ADC041             1431.832         3
     GRASS_PASTURE            0.981  1403.975
2001 45_ADC042             1406.261         3
     GRASS_PASTURE            0.920  1293.762
2001 45_ADC043             2265.728         4
     GRASS_PASTURE            0.748  1694.203
2001 45_ADC044             2175.626         4
     GRASS_PASTURE            0.837  1821.045
2001 39_ADC045             1324.179         4
     SMALL_GRAINS             0.008    10.233
2001 45_ADC046             1171.803         3
     SMALL_GRAINS             0.023    26.863
2001 45_ADC048             2794.639         4
     GRASS_PASTURE            0.737  2058.816
2002 360645                 355.962         1
     GRASS_PASTURE            1.000   355.962
2002 360649                 736.309         1
     GRASS_PASTURE            1.000   736.309
2002 360660                 298.978         1
     GRASS_PASTURE            1.000   298.978
2002 360662                1184.399         2
     ALFALFA                  0.085   100.517
2002 360800                 209.766         1
     GRASS_PASTURE            1.000   209.766
2002 360801                 328.314         1
     GRASS_PASTURE            1.000   328.314
2002 360868                 130.260         1
     GRASS_PASTURE            1.000   130.260
2002 380516                 269.791         4
     ALFALFA                  0.000     0.000
2002 380528                 273.248         3
     ALFALFA                  0.000     0.000
2002 380545                 170.351         1
     GRASS_PASTURE            1.000   170.351
2002 380569                 656.492         2
     ALFALFA                  0.000     0.000
2002 380606                 119.565         1
     GRASS_PASTURE            1.000   119.565
2002 380618                 195.712         2
     ALFALFA                  0.000     0.000
2002 380639                 195.479         1
     GRASS_PASTURE            1.000   195.479
2002 380651                 470.791         3
     ALFALFA                  0.000     0.000
2002 380659                  42.218         2
     GRASS_PASTURE            0.165     6.984
2002 380663                 150.226         3
     ALFALFA                  0.000     0.000
2002 380688                 130.362         2
     ALFALFA                  0.000     0.000
2002 380800                 139.596         1
     GRASS_PASTURE            1.000   139.596
2002 380822                  62.079         1
     GRASS_PASTURE            1.000    62.079
2002 380838                  32.492         1
     GRASS_PASTURE            1.000    32.492
2002 380840                 320.663         2
     ALFALFA                  0.000     0.000
2002 380861                 164.286         1
     GRASS_PASTURE            1.000   164.286
2002 380880                 785.098         2
     ALFALFA                  0.000     0.000
2002 380881                 253.908         2
     ALFALFA                  0.000     0.000
2002 380890                 136.346         1
     GRASS_PASTURE            1.000   136.346
2002 380893                 512.291         2
     ALFALFA                  0.000     0.000
2002 380902                 995.745         3
     ALFALFA                  0.000     0.000
2002 380925                 520.167         3
     ALFALFA                  0.000     0.000
2002 380930                  34.005         1
     GRASS_PASTURE            1.000    34.005
2002 380939                 125.433         2
     ALFALFA                  0.000     0.000
2002 380959                 141.837         2
     ALFALFA                  0.000     0.000
2002 380966                  91.325         3
     ALFALFA                  0.000     0.000
2002 380968                 296.481         3
     ALFALFA                  0.000     0.000
2002 380981                 202.986         2
     GRASS_PASTURE            1.000   202.986
2002 380989                  70.913         1
     GRASS_PASTURE            1.000    70.913
2002 380994                 174.339         2
     ALFALFA                  0.000     0.000
2002 380996                 172.852         2
     ALFALFA                  0.000     0.000
2002 381012                 181.382         2
     ALFALFA                  0.000     0.000
2002 381018                  16.566         2
     ALFALFA                  0.000     0.000
2002 381038                1176.064         3
     ALFALFA                  0.000     0.000
2002 381062                  76.950         2
     ALFALFA                  0.000     0.000
2002 381066                 424.051         2
     ALFALFA                  0.000     0.000
2002 381095                 331.320         1
     GRASS_PASTURE            1.000   331.320
2002 381101                  38.758         1
     GRASS_PASTURE            1.000    38.758
2002 381104                 180.260         2
     ALFALFA                  0.000     0.000
2002 381121                  22.627         1
     GRASS_PASTURE            1.000    22.627
2002 381132                   7.833         1
     GRASS_PASTURE            1.000     7.833
2002 381481                 345.953         3
     ALFALFA                  0.000     0.000
2002 381661                 306.270         2
     ALFALFA                  0.000     0.000
2002 390532                 112.767         3
     CORN_GRAIN               0.020     2.244
2002 390539                  92.705         1
     GRASS_PASTURE            1.000    92.705
2002 390540                 555.061         2
     GRASS_PASTURE            0.875   485.511
2002 390548                  58.607         1
     GRASS_PASTURE            1.000    58.607
2002 390562                 111.154         1
     GRASS_PASTURE            1.000   111.154
2002 390585                 138.149         2
     GRASS_PASTURE            0.927   128.045
2002 390590                 135.376         2
     GRASS_PASTURE            1.000   135.376
2002 390610                 346.992         1
     GRASS_PASTURE            1.000   346.992
2002 390612                1097.901         5
     ALFALFA                  0.027    30.099
2002 390635                 127.131         3
     ALFALFA                  0.733    93.200
2002 390638                  58.381         1
     GRASS_PASTURE            1.000    58.381
2002 390645                1167.978         5
     ALFALFA                  0.029    33.521
2002 390825                 488.042         3
     ALFALFA                  0.386   188.297
2002 390990                 287.043         3
     ALFALFA                  0.430   123.532
2002 450514                 705.327         6
     ALFALFA                  0.000     0.000
2002 450584                 475.420         2
     ALFALFA                  0.000     0.000
2002 450616                 385.552         1
     GRASS_PASTURE            1.000   385.552
2002 450632                 445.768         2
     ALFALFA                  0.000     0.000
2002 450635                 157.981         2
     ALFALFA                  0.000     0.000
2002 450638                 144.530         2
     GRASS_PASTURE            1.000   144.530
2002 450668                 991.719         4
     ALFALFA                  0.000     0.000
2002 450685                 395.703         2
     GRASS_PASTURE            1.000   395.703
2002 450693                 738.893         2
     ALFALFA                  0.667   493.029
2002 450810                 125.679         2
     ALFALFA                  0.000     0.000
2002 450818                 690.592         3
     ALFALFA                  0.000     0.000
2002 450861                 443.143         3
     ALFALFA                  0.000     0.000
2002 450969                1864.353         5
     ALFALFA                  0.000     0.000
2002 500526                 142.766         1
     GRASS_PASTURE            1.000   142.766
2002 500539                 247.029         1
     GRASS_PASTURE            1.000   247.029
2002 500582                 392.679         1
     GRASS_PASTURE            1.000   392.679
2002 500585                 205.650         1
     GRASS_PASTURE            1.000   205.650
2002 500593                1999.619         1
     GRASS_PASTURE            1.000  1999.619
2002 500598                  50.099         1
     GRASS_PASTURE            1.000    50.099
2002 500601                 192.978         1
     GRASS_PASTURE            1.000   192.978
2002 500606                 835.312         1
     GRASS_PASTURE            1.000   835.312
2002 500612                 152.121         1
     GRASS_PASTURE            1.000   152.121
2002 500613                  61.849         1
     GRASS_PASTURE            1.000    61.849
2002 500628                 243.741         2
     ALFALFA                  0.000     0.000
2002 500632                 154.777         1
     GRASS_PASTURE            1.000   154.777
2002 500653                 445.836         1
     GRASS_PASTURE            1.000   445.836
2002 500654                 322.157         1
     GRASS_PASTURE            1.000   322.157
2002 500656                 180.006         1
     GRASS_PASTURE            1.000   180.006
2002 510529                2878.464         2
     ALFALFA                  0.000     0.000
2002 510546                 524.176         1
     GRASS_PASTURE            1.000   524.176
2002 510585                 198.078         1
     GRASS_PASTURE            1.000   198.078
2002 510594                1003.344         1
     GRASS_PASTURE            1.000  1003.344
2002 510629                 270.182         1
     GRASS_PASTURE            1.000   270.182
2002 510660                 366.511         1
     GRASS_PASTURE            1.000   366.511
2002 510699                 198.748         1
     GRASS_PASTURE            1.000   198.748
2002 510810                 386.397         2
     ALFALFA                  0.237    91.446
2002 510829                 530.631         1
     GRASS_PASTURE            1.000   530.631
2002 510831                 436.360         1
     GRASS_PASTURE            1.000   436.360
2002 510848                1693.502         1
     GRASS_PASTURE            1.000  1693.502
2002 510858                  35.332         1
     GRASS_PASTURE            1.000    35.332
2002 510880                 131.464         1
     GRASS_PASTURE            1.000   131.464
2002 510883                 145.622         1
     GRASS_PASTURE            1.000   145.622
2002 510893                 770.192         1
     GRASS_PASTURE            1.000   770.192
2002 510924                 276.273         1
     GRASS_PASTURE            1.000   276.273
2002 510934                 170.710         1
     GRASS_PASTURE            1.000   170.710
2002 510939                  35.289         1
     GRASS_PASTURE            1.000    35.289
2002 510941                 603.425         2
     GRASS_PASTURE            0.509   307.303
2002 510948                 588.144         1
     GRASS_PASTURE            1.000   588.144
2002 511149                 124.666         1
     GRASS_PASTURE            1.000   124.666
2002 520559                 123.302         1
     GRASS_PASTURE            1.000   123.302
2002 520658                  43.287         1
     GRASS_PASTURE            1.000    43.287
2002 530555                1780.727         3
     ALFALFA                  0.035    61.452
2002 530621                 497.605         1
     GRASS_PASTURE            1.000   497.605
2002 530632                  17.355         1
     GRASS_PASTURE            1.000    17.355
2002 530800                 794.342         1
     GRASS_PASTURE            1.000   794.342
2002 530883                 322.713         2
     ALFALFA                  0.741   239.189
2002 531082                 112.110         1
     GRASS_PASTURE            1.000   112.110
2002 950001               28899.877        11
     ALFALFA                  0.352 10173.014
2002 950010                2589.792         4
     ALFALFA                  0.005    12.055
2002 950011                2905.585         6
     ALFALFA                  0.013    39.195
2002 950050                4296.738         7
     ALFALFA                  0.010    43.831
2002 51_ADC001              550.505         1
     GRASS_PASTURE            1.000   550.505
2002 51_ADC002              785.286         1
     GRASS_PASTURE            1.000   785.286
2002 51_ADC003              849.278         1
     GRASS_PASTURE            1.000   849.278
2002 51_ADC004              512.210         1
     GRASS_PASTURE            1.000   512.210
2002 51_ADC005             1661.403         1
     GRASS_PASTURE            1.000  1661.403
2002 51_ADC006              625.713         1
     GRASS_PASTURE            1.000   625.713
2002 51_ADC008              875.152         1
     GRASS_PASTURE            1.000   875.152
2002 51_ADC009              896.785         1
     GRASS_PASTURE            1.000   896.785
2002 51_ADC010             1170.506         1
     GRASS_PASTURE            1.000  1170.506
2002 51_ADC011              716.316         1
     GRASS_PASTURE            1.000   716.316
2002 50_ADC012             1793.950         1
     GRASS_PASTURE            1.000  1793.950
2002 50_ADC013             1986.270         1
     GRASS_PASTURE            1.000  1986.270
2002 50_ADC014             1416.725         1
     GRASS_PASTURE            1.000  1416.725
2002 50_ADC015             1430.841         1
     GRASS_PASTURE            1.000  1430.841
2002 50_ADC016              931.044         1
     GRASS_PASTURE            1.000   931.044
2002 36_ADC018              609.981         1
     GRASS_PASTURE            1.000   609.981
2002 36_ADC019             2081.370         1
     GRASS_PASTURE            1.000  2081.370
2002 50_ADC020             1643.003         1
     GRASS_PASTURE            1.000  1643.003
2002 52_ADC021             1901.956         2
     GRASS_PASTURE            0.945  1797.471
2002 53_ADC022              307.526         1
     GRASS_PASTURE            1.000   307.526
2002 53_ADC023             1376.759         1
     GRASS_PASTURE            1.000  1376.759
2002 53_ADC024             1262.373         1
     GRASS_PASTURE            1.000  1262.373
2002 53_ADC025              822.065         1
     GRASS_PASTURE            1.000   822.065
2002 53_ADC026              957.884         2
     GRASS_PASTURE            0.948   907.916
2002 53_ADC028             1518.271         2
     GRASS_PASTURE            0.991  1504.469
2002 53_ADC032             1867.921         2
     GRASS_PASTURE            0.902  1684.993
2002 38_ADC033              703.560         4
     GRASS_PASTURE            1.000   703.560
2002 38_ADC034             1544.918         1
     GRASS_PASTURE            1.000  1544.918
2002 38_ADC035              358.106         3
     GRASS_PASTURE            1.000   358.106
2002 38_ADC036              599.973         2
     GRASS_PASTURE            1.000   599.973
2002 38_ADC038             1021.048         3
     GRASS_PASTURE            1.000  1021.048
2002 38_ADC039             1025.199         3
     GRASS_PASTURE            1.000  1025.199
2002 38_ADC040             1106.566         4
     ALFALFA                  0.000     0.000
2002 39_ADC041             1431.832         3
     GRASS_PASTURE            0.981  1403.975
2002 45_ADC042             1406.261         3
     GRASS_PASTURE            0.920  1293.762
2002 45_ADC043             2265.728         4
     GRASS_PASTURE            0.748  1694.203
2002 45_ADC044             2175.626         4
     GRASS_PASTURE            0.837  1821.045
2002 39_ADC045             1324.179         4
     SMALL_GRAINS             0.008    10.233
2002 45_ADC046             1171.803         3
     SMALL_GRAINS             0.023    26.863
2002 45_ADC048             2794.639         4
     GRASS_PASTURE            0.737  2058.816
2003 360645                 355.962         1
     GRASS_PASTURE            1.000   355.962
2003 360649                 736.309         1
     GRASS_PASTURE            1.000   736.309
2003 360660                 298.978         1
     GRASS_PASTURE            1.000   298.978
2003 360662                1184.399         2
     ALFALFA                  0.085   100.517
2003 360800                 209.766         1
     GRASS_PASTURE            1.000   209.766
2003 360801                 328.314         1
     GRASS_PASTURE            1.000   328.314
2003 360868                 130.260         1
     GRASS_PASTURE            1.000   130.260
2003 380516                 269.791         4
     ALFALFA                  0.000     0.000
2003 380528                 273.248         3
     ALFALFA                  0.000     0.000
2003 380545                 170.351         1
     GRASS_PASTURE            1.000   170.351
2003 380569                 656.492         2
     ALFALFA                  0.000     0.000
2003 380606                 119.565         1
     GRASS_PASTURE            1.000   119.565
2003 380618                 195.712         2
     ALFALFA                  0.000     0.000
2003 380639                 195.479         1
     GRASS_PASTURE            1.000   195.479
2003 380651                 470.791         3
     ALFALFA                  0.000     0.000
2003 380659                  42.218         2
     GRASS_PASTURE            0.165     6.984
2003 380663                 150.226         3
     ALFALFA                  0.000     0.000
2003 380688                 130.362         2
     ALFALFA                  0.000     0.000
2003 380800                 139.596         1
     GRASS_PASTURE            1.000   139.596
2003 380822                  62.079         1
     GRASS_PASTURE            1.000    62.079
2003 380838                  32.492         1
     GRASS_PASTURE            1.000    32.492
2003 380840                 320.663         2
     ALFALFA                  0.000     0.000
2003 380861                 164.286         1
     GRASS_PASTURE            1.000   164.286
2003 380880                 785.098         2
     ALFALFA                  0.000     0.000
2003 380881                 253.908         2
     ALFALFA                  0.000     0.000
2003 380890                 136.346         1
     GRASS_PASTURE            1.000   136.346
2003 380893                 512.291         2
     ALFALFA                  0.000     0.000
2003 380902                 995.745         3
     ALFALFA                  0.000     0.000
2003 380925                 520.167         3
     ALFALFA                  0.000     0.000
2003 380930                  34.005         1
     GRASS_PASTURE            1.000    34.005
2003 380939                 125.433         2
     ALFALFA                  0.000     0.000
2003 380959                 141.837         2
     ALFALFA                  0.000     0.000
2003 380966                  91.325         3
     ALFALFA                  0.000     0.000
2003 380968                 296.481         3
     ALFALFA                  0.000     0.000
2003 380981                 202.986         2
     GRASS_PASTURE            1.000   202.986
2003 380989                  70.913         1
     GRASS_PASTURE            1.000    70.913
2003 380994                 174.339         2
     ALFALFA                  0.000     0.000
2003 380996                 172.852         2
     ALFALFA                  0.000     0.000
2003 381012                 181.382         2
     ALFALFA                  0.000     0.000
2003 381018                  16.566         2
     ALFALFA                  0.000     0.000
2003 381038                1176.064         3
     ALFALFA                  0.000     0.000
2003 381062                  76.950         2
     ALFALFA                  0.000     0.000
2003 381066                 424.051         2
     ALFALFA                  0.000     0.000
2003 381095                 331.320         1
     GRASS_PASTURE            1.000   331.320
2003 381101                  38.758         1
     GRASS_PASTURE            1.000    38.758
2003 381104                 180.260         2
     ALFALFA                  0.000     0.000
2003 381121                  22.627         1
     GRASS_PASTURE            1.000    22.627
2003 381132                   7.833         1
     GRASS_PASTURE            1.000     7.833
2003 381481                 345.953         3
     ALFALFA                  0.000     0.000
2003 381661                 306.270         2
     ALFALFA                  0.000     0.000
2003 390532                 112.767         3
     CORN_GRAIN               0.020     2.244
2003 390539                  92.705         1
     GRASS_PASTURE            1.000    92.705
2003 390540                 555.061         2
     GRASS_PASTURE            0.875   485.511
2003 390548                  58.607         1
     GRASS_PASTURE            1.000    58.607
2003 390562                 111.154         1
     GRASS_PASTURE            1.000   111.154
2003 390585                 138.149         2
     GRASS_PASTURE            0.927   128.045
2003 390590                 135.376         2
     GRASS_PASTURE            1.000   135.376
2003 390610                 346.992         1
     GRASS_PASTURE            1.000   346.992
2003 390612                1097.901         5
     ALFALFA                  0.027    30.099
2003 390635                 127.131         3
     ALFALFA                  0.733    93.200
2003 390638                  58.381         1
     GRASS_PASTURE            1.000    58.381
2003 390645                1167.978         5
     ALFALFA                  0.029    33.521
2003 390825                 488.042         3
     ALFALFA                  0.386   188.297
2003 390990                 287.043         3
     ALFALFA                  0.430   123.532
2003 450514                 705.327         6
     ALFALFA                  0.000     0.000
2003 450584                 475.420         2
     ALFALFA                  0.000     0.000
2003 450616                 385.552         1
     GRASS_PASTURE            1.000   385.552
2003 450632                 445.768         2
     ALFALFA                  0.000     0.000
2003 450635                 157.981         2
     ALFALFA                  0.000     0.000
2003 450638                 144.530         2
     GRASS_PASTURE            1.000   144.530
2003 450668                 991.719         4
     ALFALFA                  0.000     0.000
2003 450685                 395.703         2
     GRASS_PASTURE            1.000   395.703
2003 450693                 738.893         2
     ALFALFA                  0.667   493.029
2003 450810                 125.679         2
     ALFALFA                  0.000     0.000
2003 450818                 690.592         3
     ALFALFA                  0.000     0.000
2003 450861                 443.143         3
     ALFALFA                  0.000     0.000
2003 450969                1864.353         5
     ALFALFA                  0.000     0.000
2003 500526                 142.766         1
     GRASS_PASTURE            1.000   142.766
2003 500539                 247.029         1
     GRASS_PASTURE            1.000   247.029
2003 500582                 392.679         1
     GRASS_PASTURE            1.000   392.679
2003 500585                 205.650         1
     GRASS_PASTURE            1.000   205.650
2003 500593                1999.619         1
     GRASS_PASTURE            1.000  1999.619
2003 500598                  50.099         1
     GRASS_PASTURE            1.000    50.099
2003 500601                 192.978         1
     GRASS_PASTURE            1.000   192.978
2003 500606                 835.312         1
     GRASS_PASTURE            1.000   835.312
2003 500612                 152.121         1
     GRASS_PASTURE            1.000   152.121
2003 500613                  61.849         1
     GRASS_PASTURE            1.000    61.849
2003 500628                 243.741         2
     ALFALFA                  0.000     0.000
2003 500632                 154.777         1
     GRASS_PASTURE            1.000   154.777
2003 500653                 445.836         1
     GRASS_PASTURE            1.000   445.836
2003 500654                 322.157         1
     GRASS_PASTURE            1.000   322.157
2003 500656                 180.006         1
     GRASS_PASTURE            1.000   180.006
2003 510529                2878.464         2
     ALFALFA                  0.000     0.000
2003 510546                 524.176         1
     GRASS_PASTURE            1.000   524.176
2003 510585                 198.078         1
     GRASS_PASTURE            1.000   198.078
2003 510594                1003.344         1
     GRASS_PASTURE            1.000  1003.344
2003 510629                 270.182         1
     GRASS_PASTURE            1.000   270.182
2003 510660                 366.511         1
     GRASS_PASTURE            1.000   366.511
2003 510699                 198.748         1
     GRASS_PASTURE            1.000   198.748
2003 510810                 386.397         2
     ALFALFA                  0.237    91.446
2003 510829                 530.631         1
     GRASS_PASTURE            1.000   530.631
2003 510831                 436.360         1
     GRASS_PASTURE            1.000   436.360
2003 510848                1693.502         1
     GRASS_PASTURE            1.000  1693.502
2003 510858                  35.332         1
     GRASS_PASTURE            1.000    35.332
2003 510880                 131.464         1
     GRASS_PASTURE            1.000   131.464
2003 510883                 145.622         1
     GRASS_PASTURE            1.000   145.622
2003 510893                 770.192         1
     GRASS_PASTURE            1.000   770.192
2003 510924                 276.273         1
     GRASS_PASTURE            1.000   276.273
2003 510934                 170.710         1
     GRASS_PASTURE            1.000   170.710
2003 510939                  35.289         1
     GRASS_PASTURE            1.000    35.289
2003 510941                 603.425         2
     GRASS_PASTURE            0.509   307.303
2003 510948                 588.144         1
     GRASS_PASTURE            1.000   588.144
2003 511149                 124.666         1
     GRASS_PASTURE            1.000   124.666
2003 520559                 123.302         1
     GRASS_PASTURE            1.000   123.302
2003 520658                  43.287         1
     GRASS_PASTURE            1.000    43.287
2003 530555                1780.727         3
     ALFALFA                  0.035    61.452
2003 530621                 497.605         1
     GRASS_PASTURE            1.000   497.605
2003 530632                  17.355         1
     GRASS_PASTURE            1.000    17.355
2003 530800                 794.342         1
     GRASS_PASTURE            1.000   794.342
2003 530883                 322.713         2
     ALFALFA                  0.741   239.189
2003 531082                 112.110         1
     GRASS_PASTURE            1.000   112.110
2003 950001               28899.877        11
     ALFALFA                  0.352 10173.014
2003 950010                2589.792         4
     ALFALFA                  0.005    12.055
2003 950011                2905.585         6
     ALFALFA                  0.013    39.195
2003 950050                4296.738         7
     ALFALFA                  0.010    43.831
2003 51_ADC001              550.505         1
     GRASS_PASTURE            1.000   550.505
2003 51_ADC002              785.286         1
     GRASS_PASTURE            1.000   785.286
2003 51_ADC003              849.278         1
     GRASS_PASTURE            1.000   849.278
2003 51_ADC004              512.210         1
     GRASS_PASTURE            1.000   512.210
2003 51_ADC005             1661.403         1
     GRASS_PASTURE            1.000  1661.403
2003 51_ADC006              625.713         1
     GRASS_PASTURE            1.000   625.713
2003 51_ADC008              875.152         1
     GRASS_PASTURE            1.000   875.152
2003 51_ADC009              896.785         1
     GRASS_PASTURE            1.000   896.785
2003 51_ADC010             1170.506         1
     GRASS_PASTURE            1.000  1170.506
2003 51_ADC011              716.316         1
     GRASS_PASTURE            1.000   716.316
2003 50_ADC012             1793.950         1
     GRASS_PASTURE            1.000  1793.950
2003 50_ADC013             1986.270         1
     GRASS_PASTURE            1.000  1986.270
2003 50_ADC014             1416.725         1
     GRASS_PASTURE            1.000  1416.725
2003 50_ADC015             1430.841         1
     GRASS_PASTURE            1.000  1430.841
2003 50_ADC016              931.044         1
     GRASS_PASTURE            1.000   931.044
2003 36_ADC018              609.981         1
     GRASS_PASTURE            1.000   609.981
2003 36_ADC019             2081.370         1
     GRASS_PASTURE            1.000  2081.370
2003 50_ADC020             1643.003         1
     GRASS_PASTURE            1.000  1643.003
2003 52_ADC021             1901.956         2
     GRASS_PASTURE            0.945  1797.471
2003 53_ADC022              307.526         1
     GRASS_PASTURE            1.000   307.526
2003 53_ADC023             1376.759         1
     GRASS_PASTURE            1.000  1376.759
2003 53_ADC024             1262.373         1
     GRASS_PASTURE            1.000  1262.373
2003 53_ADC025              822.065         1
     GRASS_PASTURE            1.000   822.065
2003 53_ADC026              957.884         2
     GRASS_PASTURE            0.948   907.916
2003 53_ADC028             1518.271         2
     GRASS_PASTURE            0.991  1504.469
2003 53_ADC032             1867.921         2
     GRASS_PASTURE            0.902  1684.993
2003 38_ADC033              703.560         4
     GRASS_PASTURE            1.000   703.560
2003 38_ADC034             1544.918         1
     GRASS_PASTURE            1.000  1544.918
2003 38_ADC035              358.106         3
     GRASS_PASTURE            1.000   358.106
2003 38_ADC036              599.973         2
     GRASS_PASTURE            1.000   599.973
2003 38_ADC038             1021.048         3
     GRASS_PASTURE            1.000  1021.048
2003 38_ADC039             1025.199         3
     GRASS_PASTURE            1.000  1025.199
2003 38_ADC040             1106.566         4
     ALFALFA                  0.000     0.000
2003 39_ADC041             1431.832         3
     GRASS_PASTURE            0.981  1403.975
2003 45_ADC042             1406.261         3
     GRASS_PASTURE            0.920  1293.762
2003 45_ADC043             2265.728         4
     GRASS_PASTURE            0.748  1694.203
2003 45_ADC044             2175.626         4
     GRASS_PASTURE            0.837  1821.045
2003 39_ADC045             1324.179         4
     SMALL_GRAINS             0.008    10.233
2003 45_ADC046             1171.803         3
     SMALL_GRAINS             0.023    26.863
2003 45_ADC048             2794.639         4
     GRASS_PASTURE            0.737  2058.816
2004 360645                 355.962         1
     GRASS_PASTURE            1.000   355.962
2004 360649                 736.309         1
     GRASS_PASTURE            1.000   736.309
2004 360660                 298.978         1
     GRASS_PASTURE            1.000   298.978
2004 360662                1184.399         2
     ALFALFA                  0.085   100.517
2004 360800                 209.766         1
     GRASS_PASTURE            1.000   209.766
2004 360801                 328.314         1
     GRASS_PASTURE            1.000   328.314
2004 360868                 130.260         1
     GRASS_PASTURE            1.000   130.260
2004 380516                 269.791         4
     ALFALFA                  0.000     0.000
2004 380528                 273.248         3
     ALFALFA                  0.000     0.000
2004 380545                 170.351         1
     GRASS_PASTURE            1.000   170.351
2004 380569                 656.492         2
     ALFALFA                  0.000     0.000
2004 380606                 119.565         1
     GRASS_PASTURE            1.000   119.565
2004 380618                 195.712         2
     ALFALFA                  0.000     0.000
2004 380639                 195.479         1
     GRASS_PASTURE            1.000   195.479
2004 380651                 470.791         3
     ALFALFA                  0.000     0.000
2004 380659                  42.218         2
     GRASS_PASTURE            0.165     6.984
2004 380663                 150.226         3
     ALFALFA                  0.000     0.000
2004 380688                 130.362         2
     ALFALFA                  0.000     0.000
2004 380800                 139.596         1
     GRASS_PASTURE            1.000   139.596
2004 380822                  62.079         1
     GRASS_PASTURE            1.000    62.079
2004 380838                  32.492         1
     GRASS_PASTURE            1.000    32.492
2004 380840                 320.663         2
     ALFALFA                  0.000     0.000
2004 380861                 164.286         1
     GRASS_PASTURE            1.000   164.286
2004 380880                 785.098         2
     ALFALFA                  0.000     0.000
2004 380881                 253.908         2
     ALFALFA                  0.000     0.000
2004 380890                 136.346         1
     GRASS_PASTURE            1.000   136.346
2004 380893                 512.291         2
     ALFALFA                  0.000     0.000
2004 380902                 995.745         3
     ALFALFA                  0.000     0.000
2004 380925                 520.167         3
     ALFALFA                  0.000     0.000
2004 380930                  34.005         1
     GRASS_PASTURE            1.000    34.005
2004 380939                 125.433         2
     ALFALFA                  0.000     0.000
2004 380959                 141.837         2
     ALFALFA                  0.000     0.000
2004 380966                  91.325         3
     ALFALFA                  0.000     0.000
2004 380968                 296.481         3
     ALFALFA                  0.000     0.000
2004 380981                 202.986         2
     GRASS_PASTURE            1.000   202.986
2004 380989                  70.913         1
     GRASS_PASTURE            1.000    70.913
2004 380994                 174.339         2
     ALFALFA                  0.000     0.000
2004 380996                 172.852         2
     ALFALFA                  0.000     0.000
2004 381012                 181.382         2
     ALFALFA                  0.000     0.000
2004 381018                  16.566         2
     ALFALFA                  0.000     0.000
2004 381038                1176.064         3
     ALFALFA                  0.000     0.000
2004 381062                  76.950         2
     ALFALFA                  0.000     0.000
2004 381066                 424.051         2
     ALFALFA                  0.000     0.000
2004 381095                 331.320         1
     GRASS_PASTURE            1.000   331.320
2004 381101                  38.758         1
     GRASS_PASTURE            1.000    38.758
2004 381104                 180.260         2
     ALFALFA                  0.000     0.000
2004 381121                  22.627         1
     GRASS_PASTURE            1.000    22.627
2004 381132                   7.833         1
     GRASS_PASTURE            1.000     7.833
2004 381481                 345.953         3
     ALFALFA                  0.000     0.000
2004 381661                 306.270         2
     ALFALFA                  0.000     0.000
2004 390532                 112.767         3
     CORN_GRAIN               0.020     2.244
2004 390539                  92.705         1
     GRASS_PASTURE            1.000    92.705
2004 390540                 555.061         2
     GRASS_PASTURE            0.875   485.511
2004 390548                  58.607         1
     GRASS_PASTURE            1.000    58.607
2004 390562                 111.154         1
     GRASS_PASTURE            1.000   111.154
2004 390585                 138.149         2
     GRASS_PASTURE            0.927   128.045
2004 390590                 135.376         2
     GRASS_PASTURE            1.000   135.376
2004 390610                 346.992         1
     GRASS_PASTURE            1.000   346.992
2004 390612                1097.901         5
     ALFALFA                  0.027    30.099
2004 390635                 127.131         3
     ALFALFA                  0.733    93.200
2004 390638                  58.381         1
     GRASS_PASTURE            1.000    58.381
2004 390645                1167.978         5
     ALFALFA                  0.029    33.521
2004 390825                 488.042         3
     ALFALFA                  0.386   188.297
2004 390990                 287.043         3
     ALFALFA                  0.430   123.532
2004 450514                 705.327         6
     ALFALFA                  0.000     0.000
2004 450584                 475.420         2
     ALFALFA                  0.000     0.000
2004 450616                 385.552         1
     GRASS_PASTURE            1.000   385.552
2004 450632                 445.768         2
     ALFALFA                  0.000     0.000
2004 450635                 157.981         2
     ALFALFA                  0.000     0.000
2004 450638                 144.530         2
     GRASS_PASTURE            1.000   144.530
2004 450668                 991.719         4
     ALFALFA                  0.000     0.000
2004 450685                 395.703         2
     GRASS_PASTURE            1.000   395.703
2004 450693                 738.893         2
     ALFALFA                  0.667   493.029
2004 450810                 125.679         2
     ALFALFA                  0.000     0.000
2004 450818                 690.592         3
     ALFALFA                  0.000     0.000
2004 450861                 443.143         3
     ALFALFA                  0.000     0.000
2004 450969                1864.353         5
     ALFALFA                  0.000     0.000
2004 500526                 142.766         1
     GRASS_PASTURE            1.000   142.766
2004 500539                 247.029         1
     GRASS_PASTURE            1.000   247.029
2004 500582                 392.679         1
     GRASS_PASTURE            1.000   392.679
2004 500585                 205.650         1
     GRASS_PASTURE            1.000   205.650
2004 500593                1999.619         1
     GRASS_PASTURE            1.000  1999.619
2004 500598                  50.099         1
     GRASS_PASTURE            1.000    50.099
2004 500601                 192.978         1
     GRASS_PASTURE            1.000   192.978
2004 500606                 835.312         1
     GRASS_PASTURE            1.000   835.312
2004 500612                 152.121         1
     GRASS_PASTURE            1.000   152.121
2004 500613                  61.849         1
     GRASS_PASTURE            1.000    61.849
2004 500628                 243.741         2
     ALFALFA                  0.000     0.000
2004 500632                 154.777         1
     GRASS_PASTURE            1.000   154.777
2004 500653                 445.836         1
     GRASS_PASTURE            1.000   445.836
2004 500654                 322.157         1
     GRASS_PASTURE            1.000   322.157
2004 500656                 180.006         1
     GRASS_PASTURE            1.000   180.006
2004 510529                2878.464         2
     ALFALFA                  0.000     0.000
2004 510546                 524.176         1
     GRASS_PASTURE            1.000   524.176
2004 510585                 198.078         1
     GRASS_PASTURE            1.000   198.078
2004 510594                1003.344         1
     GRASS_PASTURE            1.000  1003.344
2004 510629                 270.182         1
     GRASS_PASTURE            1.000   270.182
2004 510660                 366.511         1
     GRASS_PASTURE            1.000   366.511
2004 510699                 198.748         1
     GRASS_PASTURE            1.000   198.748
2004 510810                 386.397         2
     ALFALFA                  0.237    91.446
2004 510829                 530.631         1
     GRASS_PASTURE            1.000   530.631
2004 510831                 436.360         1
     GRASS_PASTURE            1.000   436.360
2004 510848                1693.502         1
     GRASS_PASTURE            1.000  1693.502
2004 510858                  35.332         1
     GRASS_PASTURE            1.000    35.332
2004 510880                 131.464         1
     GRASS_PASTURE            1.000   131.464
2004 510883                 145.622         1
     GRASS_PASTURE            1.000   145.622
2004 510893                 770.192         1
     GRASS_PASTURE            1.000   770.192
2004 510924                 276.273         1
     GRASS_PASTURE            1.000   276.273
2004 510934                 170.710         1
     GRASS_PASTURE            1.000   170.710
2004 510939                  35.289         1
     GRASS_PASTURE            1.000    35.289
2004 510941                 603.425         2
     GRASS_PASTURE            0.509   307.303
2004 510948                 588.144         1
     GRASS_PASTURE            1.000   588.144
2004 511149                 124.666         1
     GRASS_PASTURE            1.000   124.666
2004 520559                 123.302         1
     GRASS_PASTURE            1.000   123.302
2004 520658                  43.287         1
     GRASS_PASTURE            1.000    43.287
2004 530555                1780.727         3
     ALFALFA                  0.035    61.452
2004 530621                 497.605         1
     GRASS_PASTURE            1.000   497.605
2004 530632                  17.355         1
     GRASS_PASTURE            1.000    17.355
2004 530800                 794.342         1
     GRASS_PASTURE            1.000   794.342
2004 530883                 322.713         2
     ALFALFA                  0.741   239.189
2004 531082                 112.110         1
     GRASS_PASTURE            1.000   112.110
2004 950001               28899.877        11
     ALFALFA                  0.352 10173.014
2004 950010                2589.792         4
     ALFALFA                  0.005    12.055
2004 950011                2905.585         6
     ALFALFA                  0.013    39.195
2004 950050                4296.738         7
     ALFALFA                  0.010    43.831
2004 51_ADC001              550.505         1
     GRASS_PASTURE            1.000   550.505
2004 51_ADC002              785.286         1
     GRASS_PASTURE            1.000   785.286
2004 51_ADC003              849.278         1
     GRASS_PASTURE            1.000   849.278
2004 51_ADC004              512.210         1
     GRASS_PASTURE            1.000   512.210
2004 51_ADC005             1661.403         1
     GRASS_PASTURE            1.000  1661.403
2004 51_ADC006              625.713         1
     GRASS_PASTURE            1.000   625.713
2004 51_ADC008              875.152         1
     GRASS_PASTURE            1.000   875.152
2004 51_ADC009              896.785         1
     GRASS_PASTURE            1.000   896.785
2004 51_ADC010             1170.506         1
     GRASS_PASTURE            1.000  1170.506
2004 51_ADC011              716.316         1
     GRASS_PASTURE            1.000   716.316
2004 50_ADC012             1793.950         1
     GRASS_PASTURE            1.000  1793.950
2004 50_ADC013             1986.270         1
     GRASS_PASTURE            1.000  1986.270
2004 50_ADC014             1416.725         1
     GRASS_PASTURE            1.000  1416.725
2004 50_ADC015             1430.841         1
     GRASS_PASTURE            1.000  1430.841
2004 50_ADC016              931.044         1
     GRASS_PASTURE            1.000   931.044
2004 36_ADC018              609.981         1
     GRASS_PASTURE            1.000   609.981
2004 36_ADC019             2081.370         1
     GRASS_PASTURE            1.000  2081.370
2004 50_ADC020             1643.003         1
     GRASS_PASTURE            1.000  1643.003
2004 52_ADC021             1901.956         2
     GRASS_PASTURE            0.945  1797.471
2004 53_ADC022              307.526         1
     GRASS_PASTURE            1.000   307.526
2004 53_ADC023             1376.759         1
     GRASS_PASTURE            1.000  1376.759
2004 53_ADC024             1262.373         1
     GRASS_PASTURE            1.000  1262.373
2004 53_ADC025              822.065         1
     GRASS_PASTURE            1.000   822.065
2004 53_ADC026              957.884         2
     GRASS_PASTURE            0.948   907.916
2004 53_ADC028             1518.271         2
     GRASS_PASTURE            0.991  1504.469
2004 53_ADC032             1867.921         2
     GRASS_PASTURE            0.902  1684.993
2004 38_ADC033              703.560         4
     GRASS_PASTURE            1.000   703.560
2004 38_ADC034             1544.918         1
     GRASS_PASTURE            1.000  1544.918
2004 38_ADC035              358.106         3
     GRASS_PASTURE            1.000   358.106
2004 38_ADC036              599.973         2
     GRASS_PASTURE            1.000   599.973
2004 38_ADC038             1021.048         3
     GRASS_PASTURE            1.000  1021.048
2004 38_ADC039             1025.199         3
     GRASS_PASTURE            1.000  1025.199
2004 38_ADC040             1106.566         4
     ALFALFA                  0.000     0.000
2004 39_ADC041             1431.832         3
     GRASS_PASTURE            0.981  1403.975
2004 45_ADC042             1406.261         3
     GRASS_PASTURE            0.920  1293.762
2004 45_ADC043             2265.728         4
     GRASS_PASTURE            0.748  1694.203
2004 45_ADC044             2175.626         4
     GRASS_PASTURE            0.837  1821.045
2004 39_ADC045             1324.179         4
     SMALL_GRAINS             0.008    10.233
2004 45_ADC046             1171.803         3
     SMALL_GRAINS             0.023    26.863
2004 45_ADC048             2794.639         4
     GRASS_PASTURE            0.737  2058.816
