[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "CACHE LA POUDRE RIVER AT FORT COLLINS, CO. 06752260"

[SubProduct 1]

GraphType = "Line"
LeftYAxisLegendPosition = "Right"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LegendFormat = "%z"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "06752260.USGS.Streamflow.Month[1976]~HydroBase"
TSAlias = "06752260_1976"

[Data 1.2]

TSID = "06752260.USGS.Streamflow.Month[1977]~HydroBase"
TSAlias = "06752260_1977"

[Data 1.3]

TSID = "06752260.USGS.Streamflow.Month[1978]~HydroBase"
TSAlias = "06752260_1978"

[Data 1.4]

TSID = "06752260.USGS.Streamflow.Month[1979]~HydroBase"
TSAlias = "06752260_1979"

[Data 1.5]

TSID = "06752260.USGS.Streamflow.Month[1980]~HydroBase"
TSAlias = "06752260_1980"

[Data 1.6]

TSID = "06752260.USGS.Streamflow.Month[1981]~HydroBase"
TSAlias = "06752260_1981"

[Data 1.7]

TSID = "06752260.USGS.Streamflow.Month[1982]~HydroBase"
TSAlias = "06752260_1982"

[Data 1.8]

TSID = "06752260.USGS.Streamflow.Month[1983]~HydroBase"
TSAlias = "06752260_1983"

[Data 1.9]

TSID = "06752260.USGS.Streamflow.Month[1984]~HydroBase"
TSAlias = "06752260_1984"

[Data 1.10]

TSID = "06752260.USGS.Streamflow.Month[1985]~HydroBase"
TSAlias = "06752260_1985"

[Data 1.11]

TSID = "06752260.USGS.Streamflow.Month[1986]~HydroBase"
TSAlias = "06752260_1986"

[Data 1.12]

TSID = "06752260.USGS.Streamflow.Month[1987]~HydroBase"
TSAlias = "06752260_1987"

[Data 1.13]

TSID = "06752260.USGS.Streamflow.Month[1988]~HydroBase"
TSAlias = "06752260_1988"

[Data 1.14]

TSID = "06752260.USGS.Streamflow.Month[1989]~HydroBase"
TSAlias = "06752260_1989"

[Data 1.15]

TSID = "06752260.USGS.Streamflow.Month[1990]~HydroBase"
TSAlias = "06752260_1990"

[Data 1.16]

TSID = "06752260.USGS.Streamflow.Month[1991]~HydroBase"
TSAlias = "06752260_1991"

[Data 1.17]

TSID = "06752260.USGS.Streamflow.Month[1992]~HydroBase"
TSAlias = "06752260_1992"

[Data 1.18]

TSID = "06752260.USGS.Streamflow.Month[1993]~HydroBase"
TSAlias = "06752260_1993"

[Data 1.19]

TSID = "06752260.USGS.Streamflow.Month[1994]~HydroBase"
TSAlias = "06752260_1994"

[Data 1.20]

TSID = "06752260.USGS.Streamflow.Month[1995]~HydroBase"
TSAlias = "06752260_1995"

[Data 1.21]

TSID = "06752260.USGS.Streamflow.Month[1996]~HydroBase"
TSAlias = "06752260_1996"

[Data 1.22]

TSID = "06752260.USGS.Streamflow.Month[1997]~HydroBase"
TSAlias = "06752260_1997"

[Data 1.23]

TSID = "06752260.USGS.Streamflow.Month[1998]~HydroBase"
TSAlias = "06752260_1998"

[Data 1.24]

TSID = "06752260.USGS.Streamflow.Month[1999]~HydroBase"
TSAlias = "06752260_1999"

[Data 1.25]

TSID = "06752260.USGS.Streamflow.Month[2000]~HydroBase"
TSAlias = "06752260_2000"

[Data 1.26]

TSID = "06752260.USGS.Streamflow.Month[2001]~HydroBase"
TSAlias = "06752260_2001"

[Data 1.27]

TSID = "06752260.USGS.Streamflow.Month[2002]~HydroBase"
TSAlias = "06752260_2002"

[Data 1.28]

TSID = "06752260.USGS.Streamflow.Month[2003]~HydroBase"
TSAlias = "06752260_2003"

[Data 1.29]

TSID = "06752260.USGS.Streamflow.Month[2004]~HydroBase"
TSAlias = "06752260_2004"

[Data 1.30]

TSID = "06752260.USGS.Streamflow.Month[2005]~HydroBase"
TSAlias = "06752260_2005"

[Data 1.31]

TSID = "06752260.USGS.Streamflow.Month[2006]~HydroBase"
TSAlias = "06752260_2006"

[Data 1.32]

TSID = "06752260.USGS.Streamflow.Month[2007]~HydroBase"
TSAlias = "06752260_2007"

[Data 1.33]

TSID = "06752260.USGS.Streamflow.Month[2008]~HydroBase"
TSAlias = "06752260_2008"

[Data 1.34]

TSID = "06752260.USGS.Streamflow.Month[2009]~HydroBase"
TSAlias = "06752260_2009"

[Data 1.35]

TSID = "06752260.USGS.Streamflow.Month[2010]~HydroBase"
TSAlias = "06752260_2010"

[Data 1.36]

TSID = "06752260.USGS.Streamflow.Month[2011]~HydroBase"
TSAlias = "06752260_2011"

[Data 1.37]

TSID = "06752260.USGS.Streamflow.Month[2012]~HydroBase"
TSAlias = "06752260_2012"

[Data 1.38]

TSID = "06752260.USGS.Streamflow.Month[2013]~HydroBase"
TSAlias = "06752260_2013"

[Data 1.39]

TSID = "06752260.USGS.Streamflow.Month[2014]~HydroBase"
TSAlias = "06752260_2014"

[Data 1.40]

TSID = "06752260.USGS.Streamflow.Month[2015]~HydroBase"
TSAlias = "06752260_2015"

[Data 1.41]

TSID = "06752260.USGS.Streamflow.Month[2016]~HydroBase"
TSAlias = "06752260_2016"
