[Product]

MainTitleString = "Daily Reach Gain, CFS"
ProductType = "Graph"
TotalHeight = "400"
TotalWidth = "600"

[SubProduct 1]

GraphType = "Line"
LayoutYPercent = ""

[Data 1.1]

TSID = "06758500..NodeUpstreamReachGain.Day"

[SubProduct 2]

GraphType = "Line"

[Data 2.1]

TSID = "06759500..NodeUpstreamReachGain.Day"

[SubProduct 3]

GraphType = "Line"

[Data 3.1]

TSID = "06760000..NodeUpstreamReachGain.Day"
